### ISSUE TITLE
ODXTools : Admin data access in Individual Variant in the ECU

### ISSUE THREAD

**Issue by jayeshmanani** [mercedes-benz/odxtools#156]
can not access the admin data for the individual variant inside the one ECU, It seems it is not available now, as able to access the admin data in the diag layer container for the doc revision for ECU, but not individual variants admin data like doc revisions in one of the variants of the ECU - like for boot variant, base variant etc.

**Comment by andlaus** [comment]
are you sure that you use the latest release? Like all diagnostic layers, ECU variants should feature an `admin_data` property from odxtools version 4.0 on:

(cf. https://github.com/mercedes-benz/odxtools/blame/main/odxtools/diaglayer.py#L240-L242, https://github.com/mercedes-benz/odxtools/blob/main/odxtools/diaglayerraw.py#L46, and https://github.com/mercedes-benz/odxtools/blob/main/odxtools/diaglayerraw.py#L91-L94)

**Comment by jayeshmanani** [comment]
Yeah Found It
