### ISSUE TITLE
setup.py requires very old python-can dependancy

### ISSUE THREAD

**Issue by stoyan-SLN** [mercedes-benz/odxtools#174]
requires_list = [
    "bitstruct >= 6.0.0",
    "argparse_addons",
    "PyInquirer",
    "jinja2",
    "python-can < 4.0",

Since python-can 4.0 and later is strongly recommended by the python-can community, what is the reason for odxtools to require an old version which has many unresolved issues?

Do you plan to be compatible with  python-can 4.0 and later?

**Comment by andlaus** [comment]
> Do you plan to be compatible with python-can 4.0 and later?

we already are. this restriction is an artifact of a very old odxtools version...

**Comment by stoyan-SLN** [comment]
Thank you for the fast reaction!

When should we expect a new release?

**Comment by andlaus** [comment]
release done...
