### ISSUE TITLE
ModuleNotFoundError: No module named 'odxtools.compumethods' with v5.0.0

### ISSUE THREAD

**Issue by matthtran** [mercedes-benz/odxtools#179]
Installation using `pip` succeeds, but there's an error on import. Looking at the files and on https://pypi-browser.org/package/odxtools/odxtools-5.0.0.tar.gz, it appears the `compumethods` folder is not included in the package.

**Comment by andlaus** [comment]
okay, I hope to have fixed this with version 5.0.4. If the issue persists, feel free to reopen it...
