### ISSUE TITLE
Can we decode a response hex payload given the PDX file?

### ISSUE THREAD

**Issue by chenyin0126** [mercedes-benz/odxtools#204]
I know there is a ecu.decode logic, but the input has to be bytes array. It looks like we have to convert the long hex payload to bytes array, can we:
1. provide another decode that given long hex payload and pdx file?
2. Make a function to divide the long response hex payload to bytes array?

**Comment by andlaus** [comment]
you mean something like
```python
response_hex = "00112233"
ecu.decode_response(bytes.fromhex(response_hex)
```
?

**Comment by andlaus** [comment]
I'll close this for now. if the snippet above does not work for you, feel free to re-open...
