### ISSUE TITLE
load a ".odx-d" file(diag-layer-container) failed due to ID-REF to an object from another ".odx-d"(functional group) file

### ISSUE THREAD

**Issue by chenyin0126** [mercedes-benz/odxtools#224]
I tried to load a base-variant .odx-d file to generate a database object, with `def load_file(file_name: str) -> Database:`, this file contains diag-layer-container information, 

,however, the load file failed due to 

`\"ODXLINK reference OdxLinkRef('FGL_UDS') could not be resolved for any of the document fragments [OdxDocFragment(doc_name='DLC_FGL_UDS', doc_type='CONTAINER')]\`

the reason for this is we only make one odx-d file as input to load the file, but this base variant odx-d file contains a ref to the other functional group odx-d file. So the load file process failed. 

Can we make more than one file as input to load odx-d? if we can load both base variant and functional group, we can avoid this issue; or can we make load function to ignore if we cannot link to the object from another file?

**Comment by andlaus** [comment]
as a quick fix to get the file loading, you can try to use the [non-strict mode](https://github.com/mercedes-benz/odxtools#using-the-non-strict-mode). The resulting database object might or might not be very useful, though.

a better solution is allowing to specify a list of file names to [`load_file()`]()https://github.com/mercedes-benz/odxtools/blob/main/odxtools/load_file.py#L7) and its friends. Such patches would be highly welcome...

**Comment by andlaus** [comment]
barring bugs, this has been implemented via #307. I'll close this for now...
