### ISSUE TITLE
Handle Special Data Groups

### ISSUE THREAD

**Issue by andlaus** [mercedes-benz/odxtools#34]
SDGs are a way to put user-defined information into the ODX database. odxtools currently completely ignores them...

Andreas Lauser &lt;<andreas.lauser@mercedes-benz.com>&gt;, on behalf of [MBition GmbH](https://mbition.io/).
[Provider Information](https://github.com/mercedes-benz/daimler-foss/blob/master/PROVIDER_INFORMATION.md)

**Comment by dmholtz** [comment]
PR #99 should resolve this issue.

**Comment by andlaus** [comment]
correct
