### ISSUE TITLE
__message_format_lines crash with overlapping signals

### ISSUE THREAD

**Issue by kayoub5** [mercedes-benz/odxtools#70]
I am not sure how that function works to fix the issue myself, but I could provide what the struct that caused the issue look like

All have byte position = 0
| Param  | bit position | bit length |
|---|---|---|
| 1 | 0 | 2 |
| 2 | 2 | 2 |
| 3 | 3 | 2 |
| 4 | 5 | 1 |
| 5 | 6 | 1 |
| 6 | 7 | 1 |

Stack trace
```
            next_line = f"{(len(indent_for_byte_numbering) - 1 - len(str(byte))) * ' '}{byte} "

            for bit in range(8):
                assert 8 * byte + bit <= breakpoint

                if 8 * byte + bit == breakpoint:
                    # END-OF-PDU fields do not exhibit a fixed bit
                    # length, so they need special treatment here
                    dct = None
>                   if hasattr(params[i], 'dop'):
E                   IndexError: list index out of range
```

**Comment by andlaus** [comment]
I suppose that in order to help you here I would need a dataset which uses this feature (e.g. an extension of the somersault example. (hint, hint ;)))

**Comment by kayoub5** [comment]
@andlaus do you have enough now to make a fix?
