### ISSUE TITLE
Support for odx-c and odx-cs file formats

### ISSUE THREAD

**Issue by smileprem** [mercedes-benz/odxtools#81]
Hi @andlaus - We have a requirement to parse the communication parameters from PDX files (odx-c and odx-cs) to be able to configure the diagnostic clients. I would like to know, if this file format support is in the road map. Please let us know.

If not planned already, we would be happy to add the functionality to this library. Please let us know if there are any concerns.

Thanks,
Prem

**Comment by dmholtz** [comment]
Having merged PR #101 #98 #92 and possibly some more I wonder if this issue is still valid?

**Comment by andlaus** [comment]
you're right: comparam subsets are fully internalized by now. closing.
